

#define MOUSEKEY_DELAY             100
#define MOUSEKEY_INTERVAL          40
#define MOUSEKEY_MAX_SPEED         8
#define MOUSEKEY_TIME_TO_MAX       20
#define MOUSEKEY_WHEEL_MAX_SPEED   8
#define MOUSEKEY_WHEEL_TIME_TO_MAX 18

#define TAPPING_TERM 432
#define TAP_CODE_DELAY 100
#define PERMISSIVE_HOLD
#define TAPPING_FORCE_HOLD
//#define TAPPING_TOGGLE 1



#ifdef AUDIO_ENABLE
  #define STARTUP_SONG SONG(EOCENE)
#endif

//#define COMBO_COUNT 3
//#define COMBO_TERM 163
